[build-system]
requires = ['setuptools >=60.0',"wheel"]
build-backend ="setuptools.build_meta"

[tool.pytest.ini_options]
testpath = ["test"]

[tool.mupy]
mupy_path  ="src"
ignore_missing_imports = true